### PR TITLE
Reduce cost of weighted lowering

### PR DESCRIPTION
**Pull request by TSGut**
@ioannisPApapadopoulos It's not quite as clean as a direct formula but it's very close (actually I guess it is a direct formula in terms of a ratio of two 2F1s...)!

This _should_ still speed things up significantly (if I haven't made a mistake in the maths ofc). Can you give it a try and let me know if further speed ups are necessary and also if the results look correct? It passes tests and my sanity checks at least.

### CODE REVIEW

**Comment by TSGut** [comment]
This is what I get now for your example

```julia
julia> using SemiclassicalOrthogonalPolynomials, ClassicalOrthogonalPolynomials

julia> t = 1.1
1.1

julia> Q₀₀ = SemiclassicalJacobi.(t, 0, 0, 0:∞);

julia> Q₁₁ = SemiclassicalJacobi.(t, 1, 1, 0:∞);

julia> L  = (Weighted.(Q₀₀) .\ Weighted.(Q₁₁));

julia> @time LL = L[1:70];
  4.524202 seconds (45.49 M allocations: 1.567 GiB, 6.03% gc time)
```

Looks a lot better to me, though I am sure more could be done.

**Comment by ioannisPApapadopoulos** [comment]
It definitely performs much better and good enough for the examples I wanted to produce for now! In the long run I might need a rethink but that's the future's problem. Thanks a million!!

**Comment by dlfivefifty** [comment]
Could do a regression test on LazyArrays.jl to find out what caused the slowdown

**Comment by TSGut** [comment]
I think we can merge this? It's a small change with big performance improvements and no real drawbacks that I can see

**Pull request merged**
