### PR TITLE
Lanczos -> Cholesky

### PR DESCRIPTION
**Pull request by TSGut**
Going to try and finish this now since a lot of the dependencies have been merged recently. Continued from https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/pull/70

### CODE REVIEW

**Comment by TSGut** [comment]
Still need to fix a bunch of stuff but the core functionality works now and we can do

```julia
julia> t = 1.1
1.1

julia> P = SemiclassicalJacobi.(t, 2, 3, 0:100)
101-element SemiclassicalOrthogonalPolynomials.SemiclassicalJacobiFamily{Float64, Int64, Int64, UnitRange{Int64}}:
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^0.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^1.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^2.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^3.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^4.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^5.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^6.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^7.0
 ⋮
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^93.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^94.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^95.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^96.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^97.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^98.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^99.0
 SemiclassicalJacobi with weight x^2.0 * (1-x)^3.0 * (1.1-x)^100.0

julia> X = jacobimatrix.(P)
jacobimatrix.(101-element SemiclassicalOrthogonalPolynomials.SemiclassicalJacobiFamily{Float64, Int64, Int64, UnitRange{Int64}}):
 [0.4285714285714286 0.17496355305594127 …  … 0.17496355305594127 0.46031746031746035 …  … … ; … ; ]
 [0.3829787234042553 0.16457874306201836 …  … 0.16457874306201836 0.43317726545368346 …  … … ; … ; ]
 [0.34520276953511375 0.1541520099395171 …  … 0.1541520099395171 0.4070686945135289 …  … … ; … ; ]
 [0.3137203511990565 0.1443052686951827 …  … 0.1443052686951827 0.3826894385598206 …  … … ; … ; ]
 [0.2872361218222121 0.13526271858102465 …  … 0.13526271858102465 0.36029995792143166 …  … … ; … ; ]
 [0.26472527515546673 0.12706115066755064 …  … 0.12706115066755064 0.3399051614340066 …  … … ; … ; ]
 [0.24539686076825193 0.119657178684201 …  … 0.119657178684201 0.32138617194027685 …  … … ; … ; ]
 [0.22864307207572038 0.11297806031633609 …  … 0.11297806031633609 0.3045757382978911 …  … … ; … ; ]
 ⋮
 [0.03289677746752961 0.018612942933115786 …  … 0.018612942933115786 0.05310730941910665 …  … … ; … ; ]
 [0.032572121298083075 0.018432980472977974 …  … 0.018432980472977974 0.05259974320193956 …  … … ; … ; ]
 [0.03225380961080509 0.018256462435711624 …  … 0.018256462435711624 0.05210178066436258 …  … … ; … ; ]
 [0.03194165825529889 0.018083290937475602 …  … 0.018083290937475602 0.051613151983635884 …  … … ; … ; ]
 [0.03163549013849433 0.017913371765921237 …  … 0.017913371765921237 0.051133597343682766 …  … … ; … ; ]
 [0.031335134889829516 0.017746614209775163 …  … 0.017746614209775163 0.050662866475822105 …  … … ; … ; ]
 [0.031040428545312318 0.017582930897821904 …  … 0.017582930897821904 0.050200718224544555 …  … … ; … ; ]
 [0.03075121324923066 0.01742223764668307 …  … 0.01742223764668307 0.04974692013675538 …  … … ; … ; ]
```

**Comment by TSGut** [comment]
Okay, with all tests passing (except for coverage which I will keep pushing up as I go) this is a good point to pause and look at what works and what still needs to be done.

What works:

- Jacobi matrices
- hierarchical construction (as seen in previous comment)
- decomposition based raising operators via ldiv
- expansions and evaluations
- uses QR or Cholesky depending on even and odd integer shifts etc.

Basically 95% of the functionality of the old version is reproduced now, but...

What is missing:

- There is a new bug somewhere (not quite pinned down) that is causing powers of jacobi matrices to not compute under certain circumstances (i.e. `P.X^3` or something like that will just get stuck in an infinite loop) and a possibly unrelated adaptive cholesky bug where finite cholesky is called instead and we get stuck in an infinite loop there as well. This is currently solved by an ad hoc workaround where I decompose the Jacobi matrix via something like `Symmetric(BandedMatrix(0=>Q.X.dv, 1=>Q.X.ev)`. This is costly and should not be needed of course, so we need to fix those bugs before this can be replaced with just Q.X in all places.
- Lowering via QL. This should be next since the QL PR is pretty much ready to go once the LazyArrays PR is merged

**Comment by TSGut** [comment]
@ioannisPApapadopoulos With the last change this now will always use the step-by-step hierarchy, even if you just call 

`P = SemiclassicalJacobi(t, 1, 1, 100)`

 ensuring that it will not fail. Do keep in mind that it discards the steps if you call it in this way, so if you intend to use the individual steps later, it's still better to call 

`P = SemiclassicalJacobi.(t, 1, 1, 0:100)`

**Comment by TSGut** [comment]
All seems good here in terms of compatibility with the Q variant in ClassicalOPs. But to make this work right now requires the 0.0.2 branch of SingularIntegrals.jl which is not currently registered. I will now use this implementation to generate the plots for @ioannisPApapadopoulos

**Comment by dlfivefifty** [comment]
tagged SingularIntegrals v0.0.2

Can you remove the WIP if its ready to be reviewed?

**Comment by dlfivefifty** [comment]
Shouldn't the `neg1c` case be superseded by doing a reverse Cholesky?

**Comment by TSGut** [comment]
Ah, sorry I missed your comments here.

I guess it's a matter of design philosophy for the neg1c stuff. I any case, reverse Cholesky isn't implemented anywhere yet though (just QL) so we can't do that yet.

There is still a workaround to a bug in this PR (marked by todo comments) that I want to fix (needs changes in other packages) before merging this, unless you want to use this code then temporarily this is fine.

**Comment by TSGut** [comment]
The PR branch https://github.com/JuliaLinearAlgebra/InfiniteLinearAlgebra.jl/pull/140 will allow me to remove the workaround

**Comment by dlfivefifty** [comment]
@TSGut if this is ready to merge remove the WIP from the title

**Comment by TSGut** [comment]
just need to make sure all the dependencies are correct and tests pass first

**Comment by TSGut** [comment]
@dlfivefifty Ok looking good. Tests pass without the nasty workarounds and all the hierarchy stuff is fast and passes tests. Had to lock to Julia 1.9+ though, hope that's not an issue.

The one obvious thing that is missing is lowering via reverse Cholesky / QL but I think that can be done separately once we have implemented adaptive reverse Cholesky.

**Pull request merged**
