### PR TITLE
Work on two-interval equilibrium measure

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
@TSGut This PR has an example where we successfully compute the equilibrium measure!  The catch: there's some instability here that means we only get 10 digits of accuracy. Do you know what could be causing this?

**Comment by TSGut** [comment]
I'll take a look and see if I can spot anything. At the moment I'm getting an error from the equilibriummeasure example file here https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/pull/42/commits/935ecccc8ee2b5f99f423d7dce3e6d6fd6eec80b#diff-ff37344c00967cc4bcd1eab4b7c59758c6db3014bc8077f2cc6cf43302aecb0dR113, other than this PR do I need to be on any particular branches for other packages?

```julia

julia> ab -= jacobian(equilibriumendpointvalues,ab) \ equilibriumendpointvalues(ab)
ERROR: LoadError: MethodError: no method matching iterate(::UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}})
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:664
  iterate(::Union{LinRange, StepRangeLen}, ::Int64) at range.jl:664
  iterate(::T) where T<:Union{Base.KeySet{var"#s79", var"#s78"} where {var"#s79", var"#s78"<:Dict}, Base.ValueIterator{var"#s77"} where var"#s77"<:Dict} at dict.jl:693
  ...
Stacktrace:
  [1] iterate(::Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}})
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/indices.jl:188
  [2] iterate(A::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}, state::Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}}) (repeats 2 times)
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/abstractquasiarray.jl:363
  [3] _foldl_impl(op::Base.BottomRF{typeof(Base.add_sum)}, init::Base._InitialValue, itr::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false})
    @ Base ./reduce.jl:56
  [4] foldl_impl(op::Base.BottomRF{typeof(Base.add_sum)}, nt::Base._InitialValue, itr::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false})
    @ Base ./reduce.jl:48
  [5] mapfoldl_impl(f::typeof(identity), op::typeof(Base.add_sum), nt::Base._InitialValue, itr::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false})
    @ Base ./reduce.jl:44
  [6] mapfoldl(f::Function, op::Function, itr::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}; init::Base._InitialValue)
    @ Base ./reduce.jl:160
  [7] mapfoldl(f::Function, op::Function, itr::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false})
    @ Base ./reduce.jl:160
  [8] _mapreduce(f::Function, op::Function, #unused#::IndexCartesian, A::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false})
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:3
  [9] _mapreduce_dim(f::Function, op::Function, #unused#::Base._InitialValue, A::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}, #unused#::Colon)
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:148
 [10] mapreduce(f::Function, op::Function, A::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}; dims::Function, init::Base._InitialValue)
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:140
 [11] mapreduce(f::Function, op::Function, A::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false})
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:140
 [12] _sum(f::Function, a::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}, ::Colon; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./reducedim.jl:878
 [13] _sum(f::Function, a::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}, ::Colon)
    @ Base ./reducedim.jl:878
 [14] __sum(#unused#::ArrayLayouts.UnknownLayout, A::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}, dims::Function)
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:284
 [15] _sum(V::SubQuasiArray{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, 1, Weighted{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}, Tuple{Inclusion{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, UnionDomain{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, Tuple{ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, ClosedInterval{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}}}}, Int64}, false}, #unused#::Colon)
    @ QuasiArrays ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:267
 [16] #sum#44
    @ ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:172 [inlined]
 [17] sum
    @ ~/.julia/packages/QuasiArrays/z4zwW/src/quasireducedim.jl:172 [inlined]
 [18] equilibriumcoefficients(P::TwoBandJacobi{Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}}, a::Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}, b::Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2})
    @ Main ~/Documents/Projects/SemiclassicalOrthogonalPolynomials.jl/examples/equilibriummeasure.jl:103
 [19] equilibriumendpointvalues(ab::SVector{2, Dual{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}, Float64, 2}})
    @ Main ~/Documents/Projects/SemiclassicalOrthogonalPolynomials.jl/examples/equilibriummeasure.jl:108
 [20] static_dual_eval(#unused#::Type{ForwardDiff.Tag{typeof(equilibriumendpointvalues), Float64}}, f::typeof(equilibriumendpointvalues), x::SVector{2, Float64})
    @ ForwardDiff ~/.julia/packages/ForwardDiff/QOqCN/src/apiutils.jl:32
 [21] vector_mode_jacobian(f::Function, x::SVector{2, Float64})
    @ ForwardDiff ~/.julia/packages/ForwardDiff/QOqCN/src/jacobian.jl:181
 [22] jacobian(f::Function, x::SVector{2, Float64})
    @ ForwardDiff ~/.julia/packages/ForwardDiff/QOqCN/src/jacobian.jl:85
 [23] top-level scope
``

**Comment by dlfivefifty** [comment]
Let me get the tests passing

**Comment by dlfivefifty** [comment]
@TSGut it should work now

**Comment by TSGut** [comment]
Trying to reproduce the problem but running into my own before I get to yours. 

So I assume the example in question that's showing the instability the `V = x -> x^4 - 10x^2` one in equilibriummeasure.jl? This one:
https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/blob/021ea855731697d798ce24e907c41d6906418ff5/examples/equilibriummeasure.jl#L91
For me said example returns various errors. For one, it immediately complains that there is a BigFloat conversion required in https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/blob/021ea855731697d798ce24e907c41d6906418ff5/src/SemiclassicalOrthogonalPolynomials.jl#L49 which is there for a reason but let's say we ignore that and remove those conversions just to see what we get, I still get an error but the types involved with ForwardDiff are too verbose to sensibly reproduce here. It seems to end up in a type conversion again somewhere else, relating to 'unsafe_length()' but that might already be after the real problem has occurred.

So can you maybe just confirm that you can run the second example linked above using the Project.toml in this repo, everything else being vanilla installs? If it indeed works for you, can you share your Manifest.toml?

**Comment by dlfivefifty** [comment]
Yes, you figured out exactly what happened...

fixing this now

**Comment by dlfivefifty** [comment]
ok I got it working, using `big` instead of `BigFloat` , but still only 10 digits.

unfortunately the branches needed are a bit scattered.

**Comment by TSGut** [comment]
Okay, that's one potential error source down then. Any chance I could get a hand on a Manifest or something to investigate the problem using said scattered branches? I think I should be able to track it down if I could reproduce it.

**Comment by dlfivefifty** [comment]
Unfortunately Manifest.toml isn't very helpful for deved repos as it doesn't include the branch. But I think this should work:

https://github.com/JuliaDiff/ForwardDiff.jl/pull/525
https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/pull/52
https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/pull/45

**Comment by TSGut** [comment]
Awesome, with that I got it to run now. Can you tell me what you are comparing it to to check its accuracy?

**Comment by dlfivefifty** [comment]
Just running til convergence. One endpoint is exactly 2. It bounces around at 10 digits accuracy.

You can use RHPackage for high accuracy version

**Comment by TSGut** [comment]
Some progress on narrowing this down. Basically we can get the full accuracy by using BigFloats in one specific spot, everything else being left at Float64.

So say we introduce a separate `bigequilibriumendpointvalues()` which converts a and b to BigFloats before continuing and then converts them back to Float64 at the end (more elegantly we could do methods but the goal will obviously be to not need this in the first place so doesn't matter). Using it as follows then gives full precision:

```julia
V = x -> x^4 - 10x^2
function equilibriumcoefficients(P,a,b)
    W = Weighted(P)
    Q = associated(P)
    t = axes(W,1)
    H = @. inv(t - t')
    H̃ = Q \ (H*W)
    [1/(b*sum(W[:,1])); 2H̃[:,2:end] \( Q \ derivative.(V, b*t))]
end
function equilibriumendpointvalues(ab::SVector{2})
    a,b = ab
    P = TwoBandJacobi(a/b, -1/2, -1/2, 1/2)
    (P[[a/b,1],:])*equilibriumcoefficients(P,a,b)
end
function bigequilibriumendpointvalues(ab::SVector{2,T}) where T
    a,b = big.(ab)
    P = TwoBandJacobi(a/b, -1/2, -1/2, 1/2)
    convert.(T,(P[[a/b,1],:])*equilibriumcoefficients(P,a,b))
end

function equilibrium(ab)
    a,b = ab
    P = TwoBandJacobi(a/b, -1/2, -1/2, 1/2)
    Weighted(P) * equilibriumcoefficients(P,a,b)
end

(a,b) = ab = SVector(2.,3.)
jacobian(equilibriumendpointvalues,Float64.(ab))
equilibriumendpointvalues(ab)

for _ = 1:10
    ab -= inv(jacobian(equilibriumendpointvalues,ab))*bigequilibriumendpointvalues(ab)
end
a,b = ab
```

Interestingly neither the Jacobian nor anything else needs to use `BigFloat`. Now I'll just have to dig further into `equilibriumendpointvalues` and see in which step the precision is being lost.

**Comment by TSGut** [comment]
The error appears to originate from the associated polynomial expansion. The following yields the minimal full precision version I have so far, the only substantial change from your version is that the associated polynomials are taken with higher precision.

```julia
using SemiclassicalOrthogonalPolynomials, ClassicalOrthogonalPolynomials, ForwardDiff, Plots, StaticArrays
import ForwardDiff: derivative, jacobian, Dual
import SemiclassicalOrthogonalPolynomials: Weighted
import ClassicalOrthogonalPolynomials: associated, affine
using IntervalSets, DomainSets
using LinearAlgebra
using StaticArrays
using DualNumbers

Base.floatmin(::Type{Dual{T,V,N}}) where {T,V,N} = Dual{T,V,N}(floatmin(V))
plotly()

# If big() is causing trouble with ForwardDiff
import Base: big
import ForwardDiff: Partials
Base.big(x::Dual{T}) where {T} = Dual{T}(big(x.value), big(x.partials))
Base.big(p::Partials) = Partials(big.(p.values))

V = x -> x^4 - 10x^2
function equilibriumcoefficients(a::T,b::T) where T
    W = Weighted(TwoBandJacobi((a/b), -1/2, -1/2, 1/2)) # only generated separately to narrow down the error source
    Q = associated(TwoBandJacobi(big(a/b), -1/2, -1/2, 1/2))
    t = axes(W,1)
    tbig = axes(Q,1)
    H = @. inv(t - t')
    H̃ = Q \ (H*W)
    [1/(b*sum(W[:,1])); 2H̃[:,2:end] \( Q \ derivative.(V, b*tbig))]
end

function equilibriumendpointvalues(ab::SVector{2,T}) where T
    a,b = ab
    P = TwoBandJacobi((a/b), -1/2, -1/2, 1/2)
    convert.(T,(P[[a/b,1],:])*equilibriumcoefficients(a,b))
end

function equilibrium(ab)
    a,b = ab
    P = TwoBandJacobi(a/b, -1/2, -1/2, 1/2)
    Weighted(P) * equilibriumcoefficients(a,b)
end

(a,b) = ab = SVector(2.,3.)

for _ = 1:10
    ab -= inv(jacobian(equilibriumendpointvalues,ab))*equilibriumendpointvalues(ab)
end
a,b = ab

numsol = equilibrium(ab)
plot(numsol)

```

My knowledge of the associated polynomials stuff is a bit limited, but at a glance it seems there are a handful of operations in there that may be capping the accuracy. How is expansion to coefficients handled for associated polynomials?

**Comment by dlfivefifty** [comment]
I think it's Golub Welsch. But it doesn't seem to be the culprit:
```julia
julia> u = Q * (Q \ derivative.(V, b*x));

julia> u[0.7] - derivative(V, b*0.7)
2.220446049250313e-15
```

**Comment by dlfivefifty** [comment]
Hmm actually the coefficients are quite inaccurate:
```julia
julia> u.args[2]
ℵ₀-element LazyArrays.CachedArray{Float64, 1, Vector{Float64}, FillArrays.Zeros{Float64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}} with indices OneToInf():
 -8.06681371941113e-12
 -4.619482981699382
 -2.458075702811415e-12
  3.5893766658356676
 -5.423329501286408e-13
  7.703970496588466e-16
 -1.1647052074462766e-13
 -1.8907379621394452e-15
 -2.5109525342648986e-14
  6.449215682392526e-16
 -5.541623945080653e-15
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  ⋮
```
The first entry should be 0.

**Comment by dlfivefifty** [comment]
Bizarre:
```julia
julia> (Q[:,Base.OneTo(10)] \ Vp.(b*x))[1]
3.0352402588327395e-13

julia> (Q[:,Base.OneTo(20)] \ Vp.(b*x))[1]
-6.909921823027912e-10

julia> (Q[:,Base.OneTo(30)] \ Vp.(b*x))[1]
-1.566279647092592e-7

julia> (Q[:,Base.OneTo(40)] \ Vp.(b*x))[1]
-6.928359034625201e-18
```

**Comment by dlfivefifty** [comment]
For record: https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/pull/47

**Pull request merged**
